name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Inject GA_TRACKING_ID
      run: |
        echo "window.GA_TRACKING_ID = '${{ secrets.GA_TRACKING_ID }}';" > config.js
        find . -name '*.html' -exec sed -i 's/YOUR_TRACKING_ID/${{ secrets.GA_TRACKING_ID }}/g' {} +

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
